Import music data
GSPuniani/eek-anderson-media pull request #26
Opened 2021-09-29 00:43 UTC by JosephCottingham

2021-09-29 00:44 UTC, JosephCottingham commented
Please do a squash and merge!

2021-09-29 02:15 UTC, tristann3 commented on music_lib_search_tool/music_lib_search_tool/apps/music_collection_search/csv_cleaner.py
> +    master_owner_model = None
update to master_owner_models_list

2021-09-29 02:15 UTC, tristann3 commented on music_lib_search_tool/music_lib_search_tool/apps/music_collection_search/csv_cleaner.py
> +    time_signature_model = None
update to time_signature_models_list

2021-09-29 02:15 UTC, tristann3 commented on music_lib_search_tool/music_lib_search_tool/apps/music_collection_search/csv_cleaner.py
> +    mode_model = None
update ro mode_models_list

2021-09-29 02:17 UTC, tristann3 requested changes
Looks good, I'd like to see some improvements on spacing between blocks for readability but I don't think that is neccesary right now. Please fix variable consitency then you'll get my thumbs up

2021-09-29 19:48 UTC, GSPuniani reviewed
Should we leave in is_exclusive as a nullable field for now instead of deleting it? I think we will use it later with the exclusive contact info.

2021-09-30 12:09 UTC, tristann3 commented
> Should we leave in is_exclusive as a nullable field for now instead of deleting it? I think we will use it later with the exclusive contact info.

I don't think we should do anything Niko doesn't explicitly ask of us. We are already pushing deadlines, lets get this up and running asap.

2021-09-30 17:24 UTC, merged